/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Ferrox Ecosystem",
  "tagline": "Documentation and Guides for Ferrox, YALC and more",
  "favicon": "img/logo.jpg",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true,
      "siteStorageNamespacing": true,
      "fasterByDefault": true,
      "mdx1CompatDisabledByDefault": true
    },
    "experimental_vcs": {},
    "experimental_router": "browser",
    "faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true,
      "rspackPersistentCache": true,
      "ssgWorkerThreads": true,
      "gitEagerVcs": true
    }
  },
  "url": "https://ferrox-rust.dev",
  "baseUrl": "/",
  "organizationName": "AI-Autistic-Intelligence",
  "projectName": "ferrox-docs",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "id": "ferrox",
          "path": "docs/ferrox",
          "routeBasePath": "docs/ferrox",
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/AI-Autistic-Intelligence/ferrox-docs/tree/main/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ferrox-py",
        "path": "docs/ferrox-py",
        "routeBasePath": "docs/ferrox-py",
        "sidebarPath": "./sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ferrox-node",
        "path": "docs/ferrox-node",
        "routeBasePath": "docs/ferrox-node",
        "sidebarPath": "./sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ferrox-front",
        "path": "docs/ferrox-front",
        "routeBasePath": "docs/ferrox-front",
        "sidebarPath": "./sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ferrox-java",
        "path": "docs/ferrox-java",
        "routeBasePath": "docs/ferrox-java",
        "sidebarPath": "./sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "nestjs-yalc",
        "path": "docs/nestjs-yalc",
        "routeBasePath": "docs/nestjs-yalc",
        "sidebarPath": "./sidebars.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "node-yalc",
        "path": "docs/node-yalc",
        "routeBasePath": "docs/node-yalc",
        "sidebarPath": "./sidebars.js"
      }
    ]
  ],
  "themeConfig": {
    "metadata": [
      {
        "name": "keywords",
        "content": "Ferrox, NestJS, Rust, Backend, Frontend, YALC, Framework"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      }
    ],
    "image": "img/docusaurus-social-card.jpg",
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "Ferrox",
      "logo": {
        "alt": "Ferrox Logo",
        "src": "img/logo.jpg"
      },
      "items": [
        {
          "to": "/docs/ferrox/overview",
          "label": "Ferrox",
          "position": "left"
        },
        {
          "to": "/docs/ferrox-node/overview",
          "label": "Ferrox Node",
          "position": "left"
        },
        {
          "to": "/docs/ferrox-py/overview",
          "label": "Ferrox Py",
          "position": "left"
        },
        {
          "to": "/docs/ferrox-front/overview",
          "label": "Ferrox Front",
          "position": "left"
        },
        {
          "to": "/docs/ferrox-java/intro",
          "label": "Ferrox Java",
          "position": "left"
        },
        {
          "to": "/docs/nestjs-yalc/overview",
          "label": "NestJS YALC",
          "position": "left"
        },
        {
          "to": "/docs/node-yalc/overview",
          "label": "Node YALC",
          "position": "left"
        },
        {
          "href": "https://github.com/AI-Autistic-Intelligence",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Documentation",
              "to": "/docs/ferrox/overview"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "X",
              "href": "https://x.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/AI-Autistic-Intelligence/ferrox"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Ferrox Ecosystem. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": true
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": false,
      "admonitions": false,
      "headingIds": false
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
